name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        raku-version:
          - 'latest'
          - '2021.12'
        exclude:
          - os: windows-latest
            raku-version: '2021.12'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: MacOS specific setup
        if: matrix.os == 'macOS-latest'
        run: brew install openssl
      - name: Windows specific setup
        if: matrix.os == 'windows-latest'
        run: zef install --force LibraryMake
      - name: Install Dependencies
        run: |
          # install and test if need be (includes [test-depends])
          zef install .
          zef install --/test App::Prove6
      - name: Run Tests
        run: prove6 -l t
